### PR TITLE
Rename App to AppContainer

### PR DESCRIPTION
**Pull request by gphfour**
Based on #9.
Since the `@h4bff/core#App` class doesn't really represent an application but rather some kind of component container, I renamed it to `AppContainer`.

### CODE REVIEW

**Comment by spion-h4** [comment]
Hmm. Maybe AppContainer, to signal that an app needs at least one of these?

**Comment by wh4everest** [comment]
Agreed, Container to generic.

**Comment by spion** [comment]
Any status update? Are we still okay with "AppContainer" or is that name unfortunate too? (it doesn't really contain apps - its a container for the app)

**Comment by wh4everest** [comment]
> Any status update? Are we still okay with "AppContainer" or is that name unfortunate too? (it doesn't really contain apps - its a container for the app)

I think it's not good enough of a rename to be worth the effort. `App` is pretty exposed as a keyword.

Also, some things sound plain weird, like "writing a plugin for a container":

```
antivirusPlugin(container: AppContainer) { ... }
```

I say we give up on this.

**Comment by spion-h4** [comment]
ok

**Pull request closed without merging**
